### ISSUE TITLE
Need help with calculating FID scores

### ISSUE THREAD

**Issue by jacktheripper7** [arshjot/ScrabbleGAN#2]
Hey, 

Your project is a marvellous representation of the working of the paper. I really appreciate your hard work.

I know it's been a while, but I would really appreciate if you would guide through it.
Just wanted a little bit of help with the FID scores calculations. I cannot replicate your process there and I wanted to ask if you did anything differently in that. 
Running the command `bash python calculate_metrics.py -c 'path_to_checkpoint_file'` is giving me a value error as follows

<img width="775" alt="Screenshot 2022-06-11 at 3 10 44 PM" src="https://user-images.githubusercontent.com/62120656/173182594-1d2a8adf-3347-461b-91a4-22bfe2d855d3.png">

Can you give me some advice to rectify this issue. It'll mean the world to be.

Thanks and have a great day ahead.

**Comment by arshjot** [comment]
Hey,

Thank you, I'm glad you found our work useful!

Regarding your issue, it seems that `len(dataset)` is 0 which results in this error. Did you create the preprocessed data file before running the FID score calculation? You can do this by following steps 1-3 of "Steps for training the ScrabbleGAN model from scratch".

**Comment by jacktheripper7** [comment]
Hi Again, 

Thanks for replying!

As mentioned in your instructions I used your checkpoints to directly calculate the FID scores. But maybe I should try what you insisted.

Thanks for the advice and have a nice day. :D
